### ISSUE TITLE
Извините, диалог не отвечает

### ISSUE THREAD

**Issue by serg-anis** [AlexxIT/YandexDialogs#1]
Это то, чего не хватало и давно ждал!
Навык создался автоматом, после перезагрузки HA появилась ссылка на него в уведомлениях, но при попытке его активировать Алиса отвечает постоянно: "Извините, диалог не отвечает". В консоли диалогов получаю ошибку: 
1. HTTP ошибка в ответе webhook: 400. Что еще нужно настроить?

**Comment by AlexxIT** [comment]
Webhook верный? Некоторым пользователям с ошибкой создаёт

**Comment by serg-anis** [comment]
Действительно, автоматом создался webhook https://***.***.keenetic.proapi/yandex_dialogs, без "/". Исправил на https://***.***.keenetic.pro/api/yandex_dialogs, и заработало. Спасибо!

**Comment by AlexxIT** [comment]
Создание ссылки поправлено в v1.0.1
