### ISSUE TITLE
Интеграция не найдена, хотя она установлена и манифест содержит версию.

### ISSUE THREAD

**Issue by ikey-ru** [AlexxIT/YandexDialogs#14]
Не могу понять, что я не так делаю?
<img width="838" alt="1" src="https://user-images.githubusercontent.com/47115676/164992404-f4d8d298-7b29-419a-9a73-d356a92dff65.png">

<img width="1085" alt="2" src="https://user-images.githubusercontent.com/47115676/164992410-3f4013b7-6768-49bc-aa19-c38dcf4d2ab4.png">

<img width="927" alt="3" src="https://user-images.githubusercontent.com/47115676/164992418-9c3e2168-68f5-4282-84e1-50c6f68813a2.png">

**Comment by AlexxIT** [comment]
По скриншотам непонятно в чём может быть ошибка

**Comment by ikey-ru** [comment]
Ок, пока не требуется, забил. Попробую когда-нибудь заново.
