### ISSUE TITLE
узнать с какой колонки пришла команда

### ISSUE THREAD

**Issue by krivospitsky** [AlexxIT/YandexDialogs#15]
есть ли возможность определить с какой колонки пришла команда? что бы команда "включи телевизор" включило нужный

**Comment by AlexxIT** [comment]
Через диалоги это сделать невозможно. Это можно сделать через компонент Яндекс Станции.

Но конкретно под фразу "включи телевизор" возможно удобнее будет использовать интеграцию с умным домом Яндекса
