### ISSUE TITLE
HTTP ошибка в ответе webhook: 500

### ISSUE THREAD

**Issue by RomchikL** [AlexxIT/YandexDialogs#16]
HA установлен через docker. Yandex Station работает отлично. Но не получается заставить работать диалоги.
При попытке указать данные в Yandex Dialogs получаю ошибку:
Ошибка при проверке навыка:
HTTP ошибка в ответе webhook: 500

При этом навык создается в черновики, но не публикуется. Если опубликовать вручную, то Алиса говорит, мол навык не отвечает.
https://XXX.duckdns.org/api/yandex_dialogs -> 405: Method Not Allowed
В настройках Yandex Dialogs пусто, нет id.

Не могу понять, что делаю не так.

**Comment by MicroSur** [comment]
Проблемы между яндексом и дак днс.

**Comment by RomchikL** [comment]
А есть где-то информация об этом? (чтобы попытаться понять, стоит ждать, что это поправят или переходить к другому DDNS)

**Comment by RomchikL** [comment]
Все, duckdns починили, все работает, ошибки больше нет
