### ISSUE TITLE
Интеграция настраивается только один раз

### ISSUE THREAD

**Issue by Arbuzov** [AlexxIT/YandexDialogs#17]
Если при первоначальной настройке интеграции нажать отмена, в дальнейшем настроить интеграцию невозможно.

При настройке конфигурации выдается только настройка имени пользователя.
При добавлении интеграции сразу выдается сообщение что интеграция добавлена.

К настройкам можено вернуться, только после удаления интеграции в HACS и повторной установки.
[Оказывается эта ошибка воспроизводилась тут](https://github.com/AlexxIT/YandexDialogs/issues/6#issuecomment-1067714664)

**Comment by alphasixtyfive** [comment]
Увы, та же проблема.

**Comment by alphasixtyfive** [comment]
Заметил, что при первоначальной настройке в лог падают 2 сообщения:

```
Logger: frontend.js.latest.202211021
Source: components/system_log/__init__.py:256 
First occurred: 21:23:06 (1 occurrences) 
Last logged: 21:23:06

:0:0 Script error.
```

```
Logger: homeassistant.components.rest.sensor
Source: components/rest/sensor.py:170 
Integration: RESTful (documentation, issues) 
First occurred: 21:23:05 (2 occurrences) 
Last logged: 21:23:05

JSON result was not a dictionary or list with 0th element a dictionary
```

**Comment by AlexQuaken** [comment]
Подтверждаю, попробовать настроить можно только один раз. После этого удалял интеграцию и через HACS и руками из папки, ребуталася. Больше она не дает себя настроить, просто сразу говорит все создано и создается пустой. Где конфиг сохраняется чтобы можно было его удалить и попробовать еще раз, откуда-то же она знает что уже ставилась ?

**Comment by tobsik** [comment]
есть какое-то решение проблемы?

**Comment by Arbuzov** [comment]
Удалить.
Установить и настроить.
Мне не понравилось, но вот я сам бы эту проблему решать не стал.
