### ISSUE TITLE
При добавлении интеграции нет возможности указать параметры настройки

### ISSUE THREAD

**Issue by burivuh26** [AlexxIT/YandexDialogs#25]
Подобная проблема была вот в этом [issue](https://github.com/AlexxIT/YandexDialogs/issues/17), но его закрыл автор проблемы.

1. Компонент установлен через HACS
2. HASS перезагружен
3. Захожу в Устройства и Службы
4. добавляю новую интеграцию Yandex Dialogs
5. появляется сообщение о том, что «Создана запись конфигурации Yandex Dialogs». У меня нет возможности указать аккаунт яндекса, https ссылку и название навыка. 
6. В записи интеграции нет устройств или объектов, а при настройке я могу ввести только id пользователей. 

Как вернуться к возможности произвести первичную настройку компонента?

**Comment by AlexxIT** [comment]
Вероятно вы невнимательно прочли документацию. Вы прошли шаги Установка и Настройка. И не дошли до шага Использование.

**Comment by burivuh26** [comment]
Окей, вроде бы разобрался. На будущее, если кто-то столкнётся с подобной проблемой, то в настройках интеграции нужно выбрать «Добавить запись» и там будет возможность указать ссылку, аккаунт и название навыка.
