### ISSUE TITLE
Создание и подключение навыка

### ISSUE THREAD

**Issue by bartlebi** [AlexxIT/YandexDialogs#3]
Так и не смог разобраться.
HA запущен в docker на Synology. ХА проброшен в локальную сеть. Для ХА создан домен на duckdns и он открывается как извне, так и изнутри по внешнему адресу и порту. Порт изменен на нестандартный, но это не имеет значения - проверял с обоими. Настроен и работает сертификат от Let's encrypt. В configuration.yaml прописан host с ssl.
На ХА стоит оба компонента: Yandex.Stattion и Яндекс.Диалоги. Первый работает без проблем.
К сожалению, настроить подключение Яндекс.Диалогов по инструкции не удается, поскольку этот компонент не видит авторизации вторым компонентом (Yandex.Station) - файла, который необходим, в системе нету.. Пробовал вручную создать навык в Яндексе со ссылкой на компонент вида: 
`https://*.duckdns.org:38123/api/yandex_dialogs`
но в ответ Яндекс при попытке опубликовать диалог пишет:
```
Ошибки валидации:
— Endpoint URL: Ошибка реализации протокола умного дома:
availability: Not Found
devices: Not Found
devices_action: Not Found
devices_query: Not Found
user_unlink: Not Found
```
со стороны навыков есть еще настройки авторизации с такими данными:
![image](https://user-images.githubusercontent.com/68230970/107125577-dd8b5080-68bb-11eb-99f0-98b4d8a2cbe1.png)
Куда еще копать?

**Comment by AlexxIT** [comment]
Для диалогов не надо настраивать авторизацию

**Comment by bartlebi** [comment]
Задача взаимодействовать с умным домом, устройствами его, через Алису с помощью голосовых команд и получать данные от устройств (та же температура, влажность и т.п.)
Настраиваю именно навык диалогов:
![image](https://user-images.githubusercontent.com/68230970/107197859-809bb180-6a05-11eb-8999-ffc5b1b14740.png)
Авторизация не нужна, я помню, но она обязательна для настроек в самом диалоге, поэтому указал эти данные.

**Comment by bartlebi** [comment]
Блин, кажется я понял свою ошибку...

**Comment by bartlebi** [comment]
Спасибо, я тормоз) создал навык умного дома, а не диалогов, а после создания нигде об этом и не сказано.

**Comment by DivanX10** [comment]
Я при создании навыка Алиса настраивал авторизацию. Указал точно также как и для управления умным домом и все заработало.
