### ISSUE TITLE
Как запустить триггер, используя вариативный набор слов в событиях?

### ISSUE THREAD

**Issue by DivanX10** [AlexxIT/YandexDialogs#5]
Как указать в событиях варианты текста, которые нужно перехватить из события? К примеру в событиях могут быть разные слова. Допустим я говорю, расскажи про ..... или что там .... или как там .... и любые слова должны запускать триггер. 

![событие](https://user-images.githubusercontent.com/64090632/108537841-247f3a00-72ef-11eb-9172-26dfdaa758b0.JPG)

**Comment by AlexxIT** [comment]
Использовать NLU
https://yandex.ru/dev/dialogs/alice/doc/nlu.html
