### ISSUE TITLE
Приватный навык автоматически не создаётся

### ISSUE THREAD

**Issue by mavrikkk** [AlexxIT/YandexDialogs#6]
установлена последняя версия hassio на hass os. есть действующий сертификат let's. НА доступен извне по 443 порту. Установлена и работает интеграция YandexStation. Установил диалоги. Перезапускаю НА, в уведомлениях нет никакого ид. более того в логах ошибки:

Empty Yandex Login Data

и следом

Received message for unregistered webhook

никакой навык соответственно не создается и ничего не работает.

Открываю вручную путь https://my.ha.com/api/yandex_dialogs
он мне пишет "method is not allowed"

**Comment by mavrikkk** [comment]
Неужели я один такой? ) У всех все работает? Или я что то не так делаю? Версии диалогов и станции - последние на текущий момент.

**Comment by AlexxIT** [comment]
Плохо, что последние. Нужно создать диалог вручную в консоли Яндекса

**Comment by mavrikkk** [comment]
Да, я уже так и сделал. Просто не увидел открытого issue на эту тему.

**Comment by ialtuhov** [comment]
Есть два вопроса:
1. При попытке создать диалог через конфиг после перезагрузки выдает ошибку Empty Yandex Login Data.
2. При ручном создании диалога все хорошо, но связи с НА нет. Диалог говорит "Я тебя не знаю". Попробовал полностью создать ваш описанный пример, нет результата.
В чем может быть проблема?

**Comment by AlexxIT** [comment]
@ialtuhov Настройка пункт 3

**Comment by Tombraider2006** [comment]
> Неужели я один такой? ) У всех все работает? Или я что то не так делаю? Версии диалогов и станции - последние на текущий момент.

вот знакомые все люди, как я в свое время бился с твоим конфигом base_url из аддона route.. и у меня проблема аналогичная. Empty Yandex Login Data
23:11:23 – Yandex Dialogs (ERROR)

**Comment by mavrikkk** [comment]
> вот знакомые все люди

мир тесен.


> как я в свое время бился с твоим конфигом base_url из аддона route

ну ответ получили же? )


> и у меня проблема аналогичная

ответы все тут есть: создавайте вручную. Все работает идеально! Единственное, отклик довольно быстрый нужен от HA, иначе Алиса говорит, что навык не отвечает (но об этом написано в документации к данной интеграции). Мне пришлось DDNS сменить из-за этого в частности.

**Comment by AlexxIT** [comment]
Я починю автоматическое создание, как появится время

**Comment by vashilov** [comment]
+ Такая же проблема. Вручную пока не пробовал создавать, но "method is not allowed" тоже пишет.

**Comment by Arbuzov** [comment]
Да как у вас вообще что-то работает? У меня и диалог не создается и ввести в настройках можно только имя пользователя Yandex

**Comment by vladislavkovaliov** [comment]
Та же проблема. Настроил по инструкции в ручную. 
Алиса отправляет сообщение, но в Events ничего не приходит.
Может есть предложения в чем может быть проблема?

**Comment by AlexxIT** [comment]
Проверил. Автосоздание навыка работает
