### ISSUE TITLE
The custom integration 'yandex_dialogs' does not have a valid version key (None) in the manifest file and was blocked from loading.

### ISSUE THREAD

**Issue by iturtikov** [AlexxIT/YandexDialogs#8]
Не запускается после обновления homeassistant до 2021.6

[homeassistant.loader] The custom integration 'yandex_dialogs' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by mavrikkk** [comment]
откройте manifest с помощью file editor и приведите к следующему виду:

{
  "domain": "yandex_dialogs",
  "name": "Yandex Dialogs",
  "documentation": "https://github.com/AlexxIT/YandexDialogs",
  "dependencies": [],
  "codeowners": [
    "@AlexxIT"
  ],
  "requirements": [],
  "version": "1.0.2"
}

**Comment by AlexxIT** [comment]
Исправлено
