### ISSUE TITLE
Component error: yandex_dialogs - Integration 'yandex_dialogs' not found.

### ISSUE THREAD

**Issue by myrigstest** [AlexxIT/YandexDialogs#9]
После обновления Home Assistant до версии 2021.6 интеграция не находится. Переустановка не помогает.

**Comment by eagle23** [comment]
Подтвержаю.

**Comment by DivanX10** [comment]
Откройте папку интеграции и найдите файлик манифест. В него вставляем строку version и указываем версию самой интеграции. Например яндекс диалог. Смотрим какая версия и эту версию и прописываем в манифесте. Потом сохраняем и перезагружаем ХА. Все должно заработать. 
![image](https://user-images.githubusercontent.com/64090632/121370273-46a3d300-c945-11eb-9eca-da7cfeeaa903.png)
![image](https://user-images.githubusercontent.com/64090632/121370303-4c99b400-c945-11eb-8d26-dc0b8e02ac8e.png)



**Для понимания. Начиная с версии 2021.6.0 ХА запретил использовать интеграцию, если в манифесте не будет указана версия интеграции. Если в манифесте не будет указана версия интеграции, то интеграция работать не будет**

**Comment by myrigstest** [comment]
Сделал, все работает. Спасибо!
